name: Stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been open 90 days with no activity. Please remove the stale label or comment, or this will be closed in 10 days.'
        stale-pr-message: 'This pull request has been open 90 days with no activity. Please remove the stale label or comment, or this will be closed in 10 days.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 90
        days-before-close: 10
